    PREFIX ifc: <http://standards.buildingsmart.org/IFC/DEV/IFC4/ADD1/OWL#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX list: <https://w3id.org/list#>
    SELECT
         ?start
         ?ende
    WHERE {
        ?start ifc:representations_IfcProductRepresentation    ?b.
        ?b     list:hasContents                                ?c.
        ?c     ifc:items_IfcRepresentation                     ?d.
        ?d     ifc:mappingSource_IfcMappedItem                 ?e.
        ?e     ifc:mappedRepresentation_IfcRepresentationMap   ?f.
        ?f     ifc:items_IfcRepresentation                     ?g.
        ?g     ifc:outer_IfcManifoldSolidBrep                  ?h.
        ?h     ifc:cfsFaces_IfcConnectedFaceSet                ?i.
        ?i     ifc:bounds_IfcFace                              ?k.
        ?k     ifc:bound_IfcFaceBound                          ?l.
        ?l     ifc:polygon_IfcPolyLoop                         ?ende.
        }